name: bankio
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0 # For testing Bloc logic
  mockito: ^5.3.2   # For mocking dependencies

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
